import ThemeRegistry from "@/theme/ThemeRegistry";
import Header from "@/components/header/Header";
import { Roboto } from "next/font/google";
import { Box } from "@mui/material";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <Box component="html" lang="en">
      <ThemeRegistry>
        <Box component="body" className={roboto.className}>
          <Header />
          <Box component="main">{children}</Box>
        </Box>
      </ThemeRegistry>
    </Box>
  );
};

export default RootLayout;
